version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
    php-fpm:
        build:
          dockerfile: docker/php/Dockerfile
          context: .
        volumes:
            - ./src:/var/www/html